# Generated by Django 5.1.7 on 2025-03-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_url', models.URLField(unique=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('artist', models.CharField(blank=True, max_length=255)),
                ('thumbnail', models.URLField(blank=True)),
                ('mp3_url', models.URLField(blank=True)),
            ],
        ),
    ]
