# Generated by Django 5.1.7 on 2025-03-18 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_video_id_song_youtube_embed_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='video_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
